products:
  - id: blue-mug
    title: Blue Ceramic Mug
    description: >-
      A beautiful hand-crafted ceramic mug, perfect for your morning coffee. Each mug is individually glazed in our
      signature ocean-blue finish. Holds 12 oz of your favourite beverage.
    price_cents: 1200
    currency: usd
    image: ☕
    order: 1
    labels:
      - shop
      - mug
      - ceramic
      - coffee
    stripe_price_id: "price_1T2Kea5RwVcf7QBBMtoBx5e2"
    stripe_payment_link: "https://buy.stripe.com/test_fZu4gsbs84Nl5rEgcn6AM0X"
    tax_code: txcd_99999999
  - id: red-plate
    title: Red Dinner Plate
    description: >-
      A vibrant hand-painted ceramic dinner plate in bold crimson. Microwave and dishwasher safe. 10.5 inch diameter —
      perfect for everyday meals.
    price_cents: 1800
    currency: usd
    image: 🍽️
    order: 2
    labels:
      - shop
      - plate
      - ceramic
      - kitchen
    stripe_price_id: "price_1T2Keb5RwVcf7QBB9y7P3gOE"
    stripe_payment_link: "https://buy.stripe.com/test_3cI28kdAg4Nlg6i9NZ6AM0Y"
    tax_code: txcd_99999999
  - id: classic-sneakers
    title: Classic Canvas Sneakers
    description: >-
      Timeless low-top canvas sneakers with a vulcanised rubber sole. Lightweight, breathable, and available in white.
      Unisex sizing.
    price_cents: 5500
    currency: usd
    image: 👟
    order: 3
    labels:
      - shop
      - sneakers
      - footwear
      - fashion
    stripe_price_id: "price_1T2Ked5RwVcf7QBBM4mysPfT"
    stripe_payment_link: "https://buy.stripe.com/test_5kQfZa2VCa7FaLY0dp6AM0Z"
    tax_code: txcd_99999999
  - id: luxury-yacht
    title: Luxury Motor Yacht
    description: >-
      A 42-metre flybridge motor yacht with twin diesel engines, five staterooms, and a sun deck with jacuzzi. Hull in
      pearl white.
    price_cents: 19998999
    currency: usd
    image: 🛥️
    order: 4
    labels:
      - shop
      - yacht
      - luxury
      - marine
    stripe_price_id: "price_1T2Kee5RwVcf7QBBipmhyvt8"
    stripe_payment_link: "https://buy.stripe.com/test_28E8wI0Nu6Vt07kf8j6AM10"
    tax_code: txcd_20030000
